using OpenNeuro.Domain.Ions;

namespace OpenNeuro.Domain;

/// <summary>
/// Note: This is where the purpose of this app starts.
/// We are "faking" two things in this class:
/// 1. the results of an action potential.
/// 2. the number of neurotransmitters contained in this "sac".
///  
/// This class will eventuall be hooked up to the action potential.
/// For now we are "faking" the influx of calcium into the pre-synaptic
/// nerve terminal, which would normally be generated by an action potential.
/// </summary>
public class NeurotransmitterVesicles
{
    private readonly IEnumerable<Neurotransmitter> _neurotransmitters;

    public NeurotransmitterVesicles(IEnumerable<Neurotransmitter> neurotransmitters)
    {

    }

    public void Release(Calcium calcium)
    {
        if (calcium == null)
        {
            throw new ArgumentNullException
        }

            return;
    }
}