Title = "Single Neuron Configuration"

[Overview]
SimulationName = "SingleNeuron"

[Neuron]

[Neuron.PreSynaptic]
DendriteTotalNumber = "Random"
DendriteTotalNumberRandomBounds = "1000,1000000"
SpineCountPerDendrite = "Random"
SpineCountPerDendriteRandomBounds = "10,100"
RestingPotential = "-70mV"
ActionPotentialThreshold = "-55mV"
PrimaryNeurotransmitter = "Gaba"
AdditionalNeurotransmitters = ""
AxonMyelinated = "True"

[Neuron.UnderTest]
DendriteTotalNumber = "Random"
DendriteTotalNumberRandomBounds = "1000,1000000"
SpineCountPerDendrite = "Random"
SpineCountPerDendriteRandomBounds = "10,100"
RestingPotential = "-70mV"
ActionPotentialThreshold = "-55mV"
PrimaryNeurotransmitter = "Gaba"
AdditionalNeurotransmitters = ""
AxonMyelinated = "True"

[Neuron.PostSynaptic]
DendriteTotalNumber = "Random"
DendriteTotalNumberRandomBounds = "1000,1000000"
SpineCountPerDendrite = "Random"
SpineCountPerDendriteRandomBounds = "10,100"
RestingPotential = "-70mV"
ActionPotentialThreshold = "-55mV"
PrimaryNeurotransmitter = "Gaba"
AdditionalNeurotransmitters = ""
AxonMyelinated = "True"